#pragma once
static const int64_t deviceCertificateExpiresUnix = 1824176620LL;
static const char deviceHostname[] = "spotify-player";
static const char deviceCertificate[] = R"PEM(-----BEGIN CERTIFICATE-----
MIIChDCCAimgAwIBAgIJAPu0BAP++qJDMAoGCCqGSM49BAMCMCMxITAfBgNVBAMM
GFJGSUQgUGxheWVyIFByaXZhdGUgUm9vdDAeFw0yNjA5MjAwMzQzNDBaFw0yNzEw
MjIwMzQzNDBaMB8xHTAbBgNVBAMMFHNwb3RpZnktcGxheWVyLmxvY2FsMIIBSzCC
AQMGByqGSM49AgEwgfcCAQEwLAYHKoZIzj0BAQIhAP////8AAAABAAAAAAAAAAAA
AAAA////////////////MFsEIP////8AAAABAAAAAAAAAAAAAAAA////////////
///8BCBaxjXYqjqT57PrvVV2mIa8ZR0GsMxTsPY7zjw+J9JgSwMVAMSdNgiG5wST
amZ44ROdJreBn36QBEEEaxfR8uEsQkf4vOblY6RA8ncDfYEt6zOg9KE5RdiYwpZP
40Li/hp/m47n60p8D54WK84zV2sxXs7LtkBoN79R9QIhAP////8AAAAA////////
//+85vqtpxeehPO5ysL8YyVRAgEBA0IABOSvATEoFudBdS5AOYbqM5GEIHEG0e3J
uK4Top95lPGUKENW1nZRE+Sem03MiYCKs8VisrWwAtWUW+9CEW+ffXWjVjBUMB8G
A1UdEQQYMBaCFHNwb3RpZnktcGxheWVyLmxvY2FsMAwGA1UdEwEB/wQCMAAwDgYD
VR0PAQH/BAQDAgeAMBMGA1UdJQQMMAoGCCsGAQUFBwMBMAoGCCqGSM49BAMCA0kA
MEYCIQDXszZyXC6698DSBzkhniKtgAiXfoWRNTHC/PgLl+G5DQIhANkpo1UxKoCf
ZnTqYm5wJ6ck94MmbDY7m5f4JLQIEH1F
-----END CERTIFICATE-----
)PEM";
static const char devicePrivateKey[] = R"PEM(-----BEGIN PRIVATE KEY-----
MIIBeQIBADCCAQMGByqGSM49AgEwgfcCAQEwLAYHKoZIzj0BAQIhAP////8AAAAB
AAAAAAAAAAAAAAAA////////////////MFsEIP////8AAAABAAAAAAAAAAAAAAAA
///////////////8BCBaxjXYqjqT57PrvVV2mIa8ZR0GsMxTsPY7zjw+J9JgSwMV
AMSdNgiG5wSTamZ44ROdJreBn36QBEEEaxfR8uEsQkf4vOblY6RA8ncDfYEt6zOg
9KE5RdiYwpZP40Li/hp/m47n60p8D54WK84zV2sxXs7LtkBoN79R9QIhAP////8A
AAAA//////////+85vqtpxeehPO5ysL8YyVRAgEBBG0wawIBAQQgyfREnBJYK3vY
wTpLSWvIHYFLEtgVoV52eI8cYDLMP5ChRANCAATkrwExKBbnQXUuQDmG6jORhCBx
BtHtybiuE6KfeZTxlChDVtZ2URPknptNzImAirPFYrK1sALVlFvvQhFvn311
-----END PRIVATE KEY-----
)PEM";
