#!/usr/bin/env python3
"""Convert the edited logo asset to the TFT's RGB565 flash format (Pillow)."""
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
source = Image.open(ROOT / 'assets/player-head-source.png').convert('RGB')
# Bound the bright foreground to remove the generated asset's large margins.
mask = source.convert('L').point(lambda value: 255 if value > 100 else 0)
bounds = mask.getbbox()
if bounds is None:
    raise ValueError('No logo found')
x0, y0, x1, y1 = bounds
logo = source.crop((max(0,x0-6), max(0,y0-6), min(source.width,x1+6), min(source.height,y1+6)))
height = 144
width = round(logo.width * height / logo.height)
logo = logo.resize((width,height), Image.Resampling.LANCZOS)
# Quantize to the display palette. Very dark background pixels share the exact
# screen navy, avoiding a visible rectangle around the bitmap after conversion.
navy = 0x10e4
pixels = []
for r,g,b in logo.getdata():
    pixels.append(navy if max(r,g,b) < 48 else ((r>>3)<<11)|((g>>2)<<5)|(b>>3))
rows = [', '.join(f'0x{v:04x}' for v in pixels[i:i+12]) for i in range(0,len(pixels),12)]
(ROOT / 'PlayerLogo.h').write_text(
    '// Generated by tools/encode_player_logo.py; do not edit pixel data.\n'
    '#pragma once\n#include <Arduino.h>\nnamespace PlayerLogo {\n'
    f'constexpr int Width={width}, Height={height};\n'
    'const uint16_t Pixels[] PROGMEM = {\n' + ',\n'.join(rows) + '\n};\n}\n')
# Exact RGB565 round-trip thumbnail for checking the encoded asset.
preview = Image.new('RGB',(width,height))
preview.putdata([(((v>>11)&31)*255//31,((v>>5)&63)*255//63,(v&31)*255//31) for v in pixels])
preview.save(ROOT / 'assets/player-logo-tft.png')
print(f'Logo: {width} x {height}, {len(pixels)*2} bytes in flash')
