#pragma once
static const char deviceHostname[] = "spotify-player";
static const int64_t deviceCertificateExpiresUnix = 1824226617LL;
static const char deviceCertificate[] = R"PEM(-----BEGIN CERTIFICATE-----
MIIBlDCCATmgAwIBAgIJAPI3ZHQK3PnYMAoGCCqGSM49BAMCMCcxJTAjBgNVBAMM
HHNwb3RpZnktcGxheWVyIERldmljZSBJc3N1ZXIwHhcNMjYwOTIwMTczNjU3WhcN
MjcxMDIyMTczNjU3WjAfMR0wGwYDVQQDDBRzcG90aWZ5LXBsYXllci5sb2NhbDBZ
MBMGByqGSM49AgEGCCqGSM49AwEHA0IABLa7c+9TxKO5Ftethf/abvFPzfhUs8kr
IdWYtDKcKtCdlcE4MKnaWUJCN43DbOKIL0D6akBXQtiMdvAgPxly1SGjVjBUMB8G
A1UdEQQYMBaCFHNwb3RpZnktcGxheWVyLmxvY2FsMAwGA1UdEwEB/wQCMAAwDgYD
VR0PAQH/BAQDAgeAMBMGA1UdJQQMMAoGCCsGAQUFBwMBMAoGCCqGSM49BAMCA0kA
MEYCIQCwAs3NTxeaPgOPvhkz8eRPwa5dVbM4XlIf+qKGzFYW2AIhAP+LsGjJe9Aq
3JmtqzDV4WGzJG7rneWkiHfdbUBz6HAi
-----END CERTIFICATE-----
)PEM";
#define DEVICE_AUTO_CERTIFICATE 1
static const char deviceIssuerCertificate[] = R"PEM(-----BEGIN CERTIFICATE-----
MIICADCCAaagAwIBAgIJAOlAhYt6jbNFMAoGCCqGSM49BAMCMCMxITAfBgNVBAMM
GFJGSUQgUGxheWVyIFByaXZhdGUgUm9vdDAeFw0yNjA5MjAxNzM2NTdaFw0zNjA5
MTYxNzM2NTdaMCcxJTAjBgNVBAMMHHNwb3RpZnktcGxheWVyIERldmljZSBJc3N1
ZXIwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQy/y2kzIR4waSh+OmqQnXanh/o
tD1Y2JdQQMbPEVYurEpCW29zmfhuchVRJdKLPec+Nbf9UzAmvuUdrddWfMydo4G+
MIG7MBIGA1UdEwEB/wQIMAYBAf8CAQAwDgYDVR0PAQH/BAQDAgEGMB0GA1UdDgQW
BBRESu/Ube8F9dCO8c7aVQ4KlVQdYDAfBgNVHSMEGDAWgBRaEdJmNluxTAdc6kvz
sd0uC76iwzBVBgNVHR4ETjBMoBgwFoIUc3BvdGlmeS1wbGF5ZXIubG9jYWyhMDAK
hwgAAAAAAAAAADAihyAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAK
BggqhkjOPQQDAgNIADBFAiAdh+dmesaBdV8WF7ESGLEkXHSwHqm+aBarrTumSwMk
5wIhAMruhrU3i/T05ZSkA1grhKYYUuKdNmey6qGCXOG4CbzJ
-----END CERTIFICATE-----
)PEM";
static const char deviceIssuerPrivateKey[] = R"PEM(-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgvSDvVyj8v0MQTPtE
/qdcL4RnHeio9+pQ9owZr8lNwjWhRANCAAQy/y2kzIR4waSh+OmqQnXanh/otD1Y
2JdQQMbPEVYurEpCW29zmfhuchVRJdKLPec+Nbf9UzAmvuUdrddWfMyd
-----END PRIVATE KEY-----
)PEM";
static const char devicePrivateKey[] = R"PEM(-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgOYme1teCEedJGvCM
yVdxgia/0h9Gqc3MK4Rp5RdayOWhRANCAAS2u3PvU8SjuRbXrYX/2m7xT834VLPJ
KyHVmLQynCrQnZXBODCp2llCQjeNw2ziiC9A+mpAV0LYjHbwID8ZctUh
-----END PRIVATE KEY-----
)PEM";
